### ISSUE TITLE
v20 Eng. Checklist

### ISSUE THREAD

**Issue by ericorosel** [sparkfun/SSOP-DIP_Adapter_16-Pin#1]
(1) Need version number in copper

(2) Measures are in dimension layer

(3) errors present in DRC, i'm guessing most if not all are related to the measures being on the dimension layer.

(4) The silk for the name has a via right in the middle of it. Might be worth moving the silk to avoid defacing.

**Comment by ToniCorinne** [comment]
version is live. Closing this issue.
